### PR TITLE
Use material design if available

### PR DESCRIPTION
**Pull request by loganakamatsu**
There might be some visual oddities but hopefully no show-stoppers. Here's the opening screen "materialized" 

image

### CODE REVIEW

**Comment by mik3y** [comment]
Cool, let's give it a shot!

**Comment by mik3y** [comment]
@loganakamatsu Whoops, looks like this needs a rebase -- I'll leave it open since I can't get to it right now, will give it a shot later unless you beat me.

**Comment by loganakamatsu** [comment]
Oops! Thanks. It should be fixed-up now with eb8b19e

**Comment by mik3y** [comment]
Awesome, thanks again!

**Pull request merged**
