### PR TITLE
Fixes issue/129

### LINKED ISSUE #129: Crash when loading HomeActivity
I am seeing a crash when trying to launch the HomeActivity after finishing the initial app configuration tutorial.  It is actually crashing on this line:  https://github.com/Kegbot/kegbot-android/blob/0cb79c6d140e4cceb752387944edff7839d02ce9/kegtab/src/main/java/org/kegbot/app/HomeActivity.java#L93.

I think it has something to do with how the `kegbot-api.jar` library is being imported because it can't find the `KegTab` class.

I'm going to see if I can isolate the commit that possibly caused the issue with git bisect but I also think it could be an issue with the version of Android Studio (4.0) I am running.

### PR DESCRIPTION
**Pull request by rplankenhorn**
Minimal changes to fix crash for #129.

Fixes #129

### CODE REVIEW

**Comment by rplankenhorn** [comment]
@mik3y Please review.

**Comment by mik3y** [comment]
Hey, I'll try to give this a look this weekend!

**Comment by mik3y** [comment]
My apologies for the delay in merging this.

I think this is now fixed in #133 - at least, so far, cannot reproduce it. Any chance you'd like to give it a try? (Let me know if you need an apk).

**Comment by mik3y** [comment]
Fixed by #133

**Pull request closed without merging**
